# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'raising-kids'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-39298232-4'

menu:
- {name: 'About', folder: 'pages', file: 'about.html'}
#- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: '下一页'
  previous_page: '上一页'

sharing_button_prompt: 'Feel free to share!'

related_posts: '你可能也对这些感兴趣...'

post_date_prefix: 'Written on'
